/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as RThemeRouteImport } from './routes/r/theme'
import { Route as RColorRouteImport } from './routes/r/$color'
import { Route as DocsStaticThemeRouteImport } from './routes/docs/static-theme'
import { Route as DocsReferenceRouteImport } from './routes/docs/reference'
import { Route as DocsDynamicThemeRouteImport } from './routes/docs/dynamic-theme'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const RThemeRoute = RThemeRouteImport.update({
  id: '/r/theme',
  path: '/r/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const RColorRoute = RColorRouteImport.update({
  id: '/r/$color',
  path: '/r/$color',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsStaticThemeRoute = DocsStaticThemeRouteImport.update({
  id: '/static-theme',
  path: '/static-theme',
  getParentRoute: () => DocsRoute,
} as any)
const DocsReferenceRoute = DocsReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDynamicThemeRoute = DocsDynamicThemeRouteImport.update({
  id: '/dynamic-theme',
  path: '/dynamic-theme',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/charts': typeof ChartsRoute
  '/components': typeof ComponentsRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/dynamic-theme': typeof DocsDynamicThemeRoute
  '/docs/reference': typeof DocsReferenceRoute
  '/docs/static-theme': typeof DocsStaticThemeRoute
  '/r/$color': typeof RColorRoute
  '/r/theme': typeof RThemeRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/charts': typeof ChartsRoute
  '/components': typeof ComponentsRoute
  '/docs/dynamic-theme': typeof DocsDynamicThemeRoute
  '/docs/reference': typeof DocsReferenceRoute
  '/docs/static-theme': typeof DocsStaticThemeRoute
  '/r/$color': typeof RColorRoute
  '/r/theme': typeof RThemeRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/charts': typeof ChartsRoute
  '/components': typeof ComponentsRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/dynamic-theme': typeof DocsDynamicThemeRoute
  '/docs/reference': typeof DocsReferenceRoute
  '/docs/static-theme': typeof DocsStaticThemeRoute
  '/r/$color': typeof RColorRoute
  '/r/theme': typeof RThemeRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/charts'
    | '/components'
    | '/docs'
    | '/docs/dynamic-theme'
    | '/docs/reference'
    | '/docs/static-theme'
    | '/r/$color'
    | '/r/theme'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/charts'
    | '/components'
    | '/docs/dynamic-theme'
    | '/docs/reference'
    | '/docs/static-theme'
    | '/r/$color'
    | '/r/theme'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/charts'
    | '/components'
    | '/docs'
    | '/docs/dynamic-theme'
    | '/docs/reference'
    | '/docs/static-theme'
    | '/r/$color'
    | '/r/theme'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChartsRoute: typeof ChartsRoute
  ComponentsRoute: typeof ComponentsRoute
  DocsRoute: typeof DocsRouteWithChildren
  RColorRoute: typeof RColorRoute
  RThemeRoute: typeof RThemeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/r/theme': {
      id: '/r/theme'
      path: '/r/theme'
      fullPath: '/r/theme'
      preLoaderRoute: typeof RThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$color': {
      id: '/r/$color'
      path: '/r/$color'
      fullPath: '/r/$color'
      preLoaderRoute: typeof RColorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/static-theme': {
      id: '/docs/static-theme'
      path: '/static-theme'
      fullPath: '/docs/static-theme'
      preLoaderRoute: typeof DocsStaticThemeRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/reference': {
      id: '/docs/reference'
      path: '/reference'
      fullPath: '/docs/reference'
      preLoaderRoute: typeof DocsReferenceRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/dynamic-theme': {
      id: '/docs/dynamic-theme'
      path: '/dynamic-theme'
      fullPath: '/docs/dynamic-theme'
      preLoaderRoute: typeof DocsDynamicThemeRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsDynamicThemeRoute: typeof DocsDynamicThemeRoute
  DocsReferenceRoute: typeof DocsReferenceRoute
  DocsStaticThemeRoute: typeof DocsStaticThemeRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsDynamicThemeRoute: DocsDynamicThemeRoute,
  DocsReferenceRoute: DocsReferenceRoute,
  DocsStaticThemeRoute: DocsStaticThemeRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChartsRoute: ChartsRoute,
  ComponentsRoute: ComponentsRoute,
  DocsRoute: DocsRouteWithChildren,
  RColorRoute: RColorRoute,
  RThemeRoute: RThemeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
